title: Lowder Property Rentals
email: 
description: Listing of rental properties.

keywords:

host: 0.0.0.0 # GitHub will simply ignore this when you push
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lowderpropertyrentals.com" # the base hostname & protocol for your site, e.g. http://example.com

github_username:
google_analytics_tracking_id:
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
incremental: true

destination: docs

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - assets/photoshop/
   - vendor/bundle/

include: ['.htaccess']